import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Flex, Theme } from "@radix-ui/themes";
import "./globals.css";
import Sidebar from "./components/sidebar/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AgendaMed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Theme grayColor="slate">
          <Flex className="flex min-h-screen w-full bg-[#f4f5f9]">
            <Sidebar></Sidebar>
            <div className="ml-[250px] px-[45px] pt-[50px] w-full">
              {children}
            </div>
          </Flex>
        </Theme>
      </body>
    </html>
  );
}
